version: 1.0.{build}
environment:
  PYTHON: C:\Python36
install:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python -m pip install --upgrade pip

    pip install -r requirements\deployment.txt

    choco install innosetup
build_script:
- cmd: >-
    scripts\generateui.bat

    pyinstaller main.py --windowed

    iscc scripts\printer_client.iss
artifacts:
- path: scripts\Output\printer_client_setup.exe
  name: setup
deploy:
- provider: GitHub
  auth_token:
    secure: AZ4o/W1K9Z7ojmXeIaUtCfK+KrferwfKdZMkBIJOLqe+tB62UERm1JvnR/VVp6JN
  artifact: setup
  force_update: false
  on:
    APPVEYOR_REPO_TAG: true